import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { brandsColors } from "./lib/brandsColors";
import "./globals.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PUNTEKO",
  description: "Generated by create next app",
};

const brand = brandsColors.kromi;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${roboto.className}`}
      style={
        {
          "--brand-bg": brand.bg,
          "--brand-cta": brand.cta,
          "--brand-cta-color": brand.ctaColor,
          "--brand-color": brand.color,
        } as React.CSSProperties
      }
    >
      <body>{children}</body>
    </html>
  );
}
